module.exports = {
  apps: [
    {
      name: 'ataraxia-dashboard',
      script: './server.cjs',
      cwd: '/home/sefa/.openclaw/workspace/dashboard',
      interpreter: 'node',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
        PORT: 4173,
      },
      error_file: '/home/sefa/.pm2/logs/ataraxia-dashboard-error.log',
      out_file: '/home/sefa/.pm2/logs/ataraxia-dashboard-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'ataraxia-stats',
      script: './stats-server.cjs',
      cwd: '/home/sefa/.openclaw/workspace/dashboard',
      interpreter: 'node',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
        PORT: 4175,
      },
      error_file: '/home/sefa/.pm2/logs/ataraxia-stats-error.log',
      out_file: '/home/sefa/.pm2/logs/ataraxia-stats-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
}
